import Head from "next/head";
import { NextPage, NextPageContext } from "next";
import { PrismaClient, Pilot } from "@prisma/client";
import { SWRConfig } from "swr";
import IntrudersTable from "../components/IntrudersTable";

export async function getServerSideProps(context: NextPageContext) {
  const prisma = new PrismaClient();

  const pilots = await prisma.pilot.findMany({
    include: {
      drone: true,
    },
  });

  return {
    props: { pilots },
  };
}

const Home: NextPage<{ pilots: Pilot[] }> = ({ pilots }) => {
  return (
    <SWRConfig value={{ fallback: pilots }}>
      <div>
        <Head>
          <title>Reaktor Birdnest</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='w-full mx-4'>
          <IntrudersTable />
        </div>
      </div>
    </SWRConfig>
  );
};

export default Home;
