import Head from "next/head";
import { NextPage, NextPageContext } from "next";
import styles from "../styles/Home.module.css";
import { PrismaClient, Pilot } from "@prisma/client";
import useSWR, { SWRConfig } from "swr";
import List from "../components/list";

export async function getServerSideProps(context: NextPageContext) {
  const prisma = new PrismaClient();

  const pilots = await prisma.pilot.findMany({
    include: {
      drone: true,
    },
  });

  return {
    props: { pilots },
  };
}

const Home: NextPage<{ pilots: Pilot[] }> = ({ pilots }) => {
  return (
    <SWRConfig value={{ fallback: pilots }}>
      <div className={styles.container}>
        <Head>
          <title>Reaktor Birdnest</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <List />
      </div>
    </SWRConfig>
  );
};

export default Home;
