import Head from "next/head";
import { PrismaClient } from "@prisma/client";
import { SWRConfig } from "swr";
import IntrudersTable from "../components/IntrudersTable";
import DroneDisplay from "../components/DroneDisplay";
import { getDrones } from "./api/drones";
export async function getServerSideProps() {
    const prisma = new PrismaClient();
    const drones = await getDrones();
    const pilots = await prisma.pilot.findMany({
        include: {
            drone: true,
        },
    });
    return {
        props: { pilots, drones },
    };
}
const Home = ({ pilots, drones, }) => {
    return (<SWRConfig value={{ fallback: { "api/pilots": pilots, "api/drones": drones } }}>
      <div>
        <Head>
          <title>Reaktor Birdnest</title>
          <meta name='description' content='Generated by create next app'/>
          <link rel='icon' href='/favicon.ico'/>
        </Head>
        <DroneDisplay width={500} height={500}/>
        <h1 className='text-2xl font-semibold mx-4'>Intruders list</h1>
        <div className='w-full mx-4'>
          <IntrudersTable />
        </div>
      </div>
    </SWRConfig>);
};
export default Home;
//# sourceMappingURL=index.jsx.map