-- AlterTable
ALTER TABLE "Drone" ALTER COLUMN "positionY" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "positionX" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attitude" SET DATA TYPE DOUBLE PRECISION;
